[package]
name = "admin-overview-service"
version = "0.1.0"
edition = "2024"

[dependencies]
application = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
user-core = { workspace = true }
user-service = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
