[package]
name = "crawler"
version = "0.1.0"
edition = "2024"

[dependencies]
domain-primitives = { workspace = true }
application = { workspace = true }
fxrate-postgres = { workspace = true }
large-language-model = { workspace = true }
listing-source-core = { workspace = true }
listing-source-postgres = { workspace = true }
listing-source-service = { workspace = true }
localization = { workspace = true }
money = { workspace = true }
public-network-policy = { workspace = true }

platform-postgres = { workspace = true }
product-listing-core = { workspace = true }
product-listing-normalization = { workspace = true }
product-listing-postgres = { workspace = true }
product-listing-service = { workspace = true }
aws-config = { workspace = true, features = ["credentials-login"] }
aws-sdk-cloudwatchlogs = { workspace = true }
scraper = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-cloudwatch = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
schemars = { workspace = true }
async-trait = { workspace = true }
google-cloud-auth = { workspace = true }
mockall = { workspace = true }
kuchiki = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
imagesize = { workspace = true }
indexmap = { workspace = true }
tokio = { workspace = true, features = ["full", "macros"] }
spider = { workspace = true }
time = { workspace = true, features = ["serde"] }
url = { workspace = true }
uuid = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
lingua = { workspace = true }
dotenvy = { workspace = true }
bloomfilter = "3.0.1"
futures = { workspace = true }
sha2 = { workspace = true }
url-normalize = { workspace = true }
dashmap = "6.2.1"
yaml_serde = { workspace = true }

# Optional
fake = { workspace = true, optional = true }

[dev-dependencies]
crawler = { path = ".", features = ["test-data"] }
rstest = { workspace = true }
fake = { workspace = true }
serial_test = { workspace = true }
test-api = { workspace = true, features = ["postgres"] }
tokio = { workspace = true, features = ["macros", "time", "test-util"] }

[[bin]]
name = "demo-scraper"
path = "src/scraper/demo.rs"

[[bin]]
name = "demo-spider"
path = "src/spider/demo.rs"


[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "demo"
path = "src/demo.rs"

[[bin]]
name = "fetch-fixture"
path = "src/bin/fetch_fixture.rs"

[features]
default = []
test-data = [
    "application/test-data",
    "domain-primitives/test-data",
    "listing-source-core/test-data",
    "localization/test-data",
    "money/test-data",
    "product-listing-core/test-data",
    "fake",
]


[target.'cfg(not(target_env = "msvc"))'.dependencies]
libc = { workspace = true }
