# Dependabot configuration for monitoring dependency updates
# For Cargo workspaces, monitoring the root directory automatically
# detects all workspace members and their dependencies
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/Berlin

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/Berlin
    groups:
      aws-dependencies:
        patterns:
          - "aws-*"
          - "aws_*"