version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/Berlin

  - package-ecosystem: "cargo"
    directory: "/src/common"
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/Berlin
  - package-ecosystem: "cargo"
    directory: "/src/filter"
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/Berlin

  - package-ecosystem: "cargo"
    directory: "/src/item/src/item-api/src/item-api-get-item"
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/Berlin

  - package-ecosystem: "cargo"
    directory: "/src/item/src/item-core"
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/Berlin

  - package-ecosystem: "cargo"
    directory: "/src/item/src/item-index"
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/Berlin

  - package-ecosystem: "cargo"
    directory: "/src/item/src/item-lambda/src/item-lambda-write-new"
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/Berlin

  - package-ecosystem: "cargo"
    directory: "/src/item/src/item-lambda/src/item-lambda-write-update"
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/Berlin

  - package-ecosystem: "cargo"
    directory: "/src/item/src/item-write"
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/Berlin

  - package-ecosystem: "cargo"
    directory: "/src/item/src/item-read"
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/Berlin

  - package-ecosystem: "cargo"
    directory: "/src/test-api"
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/Berlin