[package]
name = "search-filter-opensearch"
version = "0.1.0"
edition = "2024"

[dependencies]
user-core = { workspace = true }
domain-primitives = { workspace = true }
application = { workspace = true }
async-trait = { workspace = true }

listing-source-core = { workspace = true }
localization = { workspace = true }
money = { workspace = true }
opensearch = { workspace = true }
product-listing-core = { workspace = true }
product-listing-opensearch = { workspace = true }
product-listing-service = { workspace = true }
platform-opensearch = { workspace = true }
search-filter-core = { workspace = true }
search-filter-service = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
time = { workspace = true, features = ["formatting", "serde"] }
thiserror = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
auction-core = { workspace = true }
fxrate-core = { workspace = true }
indexmap = { workspace = true }
serial_test = { workspace = true }
strum = { workspace = true }
test-api = { workspace = true, features = ["opensearch"] }
tokio = { workspace = true, features = ["macros", "rt"] }
url = { workspace = true }
