[package]
name = "blitzfilter-parent"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "src/common" }
filter = { path = "src/filter" }
item = { path = "src/item" }
scrape = { path = "src/scrape" }
test-api = { path = "src/test-api" }

[workspace]
members = [
    "src/common",
    "src/filter",
    "src/item",
    "src/scrape",
    "src/test-api",
]
