[package]
name = "watchlist-service"
version = "0.1.0"
edition = "2024"

[dependencies]
fake = { workspace = true, optional = true }
async-trait = { workspace = true }
application = { workspace = true }
auction-core = { workspace = true }
auction-service = { workspace = true }
domain-primitives = { workspace = true }
fxrate-core = { workspace = true }
fxrate-service = { workspace = true }
localization = { workspace = true }
money = { workspace = true }
product-listing-core = { workspace = true }
product-listing-service = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
user-core = { workspace = true }
user-service = { workspace = true }
watchlist-core = { workspace = true }

[dev-dependencies]
listing-source-core = { workspace = true }
serde-email = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
url = { workspace = true }

[features]
default = []
test-data = ["fake", "watchlist-core/test-data"]
