[package]
name = "cognito-post-confirmation"
version = "0.1.0"
edition = "2024"

[dependencies]
application = { workspace = true }
platform-observability = { workspace = true }
platform-postgres = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
aws_lambda_events = { workspace = true, features = ["cognito"] }
lambda_runtime = { workspace = true }
serde-email = { workspace = true }
user-postgres = { workspace = true }
user-service = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
serde_json = { workspace = true }
serial_test = { workspace = true }
sqlx = { workspace = true }
test-api = { workspace = true, features = ["postgres"] }
user-core = { workspace = true }
