[package]
name = "party-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
application = { workspace = true }
async-trait = { workspace = true }
domain-primitives = { workspace = true }
party-core = { workspace = true }
party-service = { workspace = true }
platform-postgres = { workspace = true }
serde-email = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
test-api = { workspace = true, features = ["postgres"] }
tokio = { workspace = true, features = ["macros", "rt"] }
