[package]
name = "item"
version = "0.1.0"
edition = "2024"

[dependencies]
item-api = { workspace = true }
item-core = { workspace = true }
item-read = { workspace = true }
item-write = { workspace = true }
item-index = { workspace = true }
item-lambda = { workspace = true }
