[package]
name = "item"
version = "0.1.0"
edition = "2024"

[dependencies]
item-api = { workspace = true }
item-core = { workspace = true }
item-opensearch = { workspace = true }
item-lambda = { workspace = true }
item-service = { workspace = true }
item-dynamodb = { workspace = true }
