[package]
name = "auction-core"
version = "0.1.0"
edition = "2024"

[dependencies]
domain-primitives = { workspace = true }
html-escape = { workspace = true }
listing-source-core = { workspace = true }
localization = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
time-tz = { workspace = true }
url = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
uuid = { workspace = true }
