[package]
name = "test_lambda"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
lambda_runtime = { workspace = true }

[[bin]]
name = "test_lambda"
path = "src/main.rs"
