[package]
name = "item-api-get-item"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../../../../../common", features = ["api"] }
item-read = { path = "../../../../src/item-read", features = ["api"] }
item-core = { path = "../../../item-core" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["json"] }
dotenvy = "0.15.7"
tokio = { version = "1.45.0", features = ["macros"] }
aws_lambda_events = { version = "0.17.0", default-features = false, features = ["apigw"] }
lambda_runtime = "0.14.3"
aws-config = "1.6.2"
aws-sdk-dynamodb = "1.74.0"
serde_json = "1.0.140"
accept-language = "3.1.0"
http = { version = "1.3.1" }

[dev-dependencies]
mockall = "0.13.1"
rstest = "0.25.0"
time = "0.3.41"
http = "1.3.1"