[package]
name = "product-listing-core"
version = "0.1.0"
edition = "2024"

[dependencies]
auction-core = { workspace = true }
strum = { workspace = true }
domain-primitives = { workspace = true }
fxrate-core = { workspace = true }
localization = { workspace = true }
money = { workspace = true }

html-escape = { workspace = true }
indexmap = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_fields = { workspace = true }
slug = { workspace = true }
listing-source-core = { workspace = true }
strum_macros = { workspace = true }
time = { workspace = true, features = ["local-offset", "macros", "formatting"] }
thiserror = { workspace = true }
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true }

# Optional
fake = { workspace = true, optional = true }

[dev-dependencies]
rstest = { workspace = true }
serde_json = { workspace = true }

[features]
default = []
test-data = ["fake", "domain-primitives/test-data", "fxrate-core/test-data", "localization/test-data", "money/test-data"]
