[package]
name = "aura-historia-cron"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
cron_tab = { workspace = true }
fxrate-postgres = { workspace = true }
google-cloud-auth = { workspace = true }
large-language-model = { workspace = true }
opensearch = { workspace = true }
platform-observability = { workspace = true }
platform-postgres = { workspace = true }
product-listing-opensearch = { workspace = true }
product-listing-postgres = { workspace = true }
search-filter-postgres = { workspace = true }
search-filter-service = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
url = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
tracing = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
sqlx = { workspace = true }
test-api = { workspace = true, features = ["postgres"] }
