use crawler::CrawlerDomainId;
use crawler::scraper::candidate_service::{ScraperCandidateService, ScraperCandidateServiceImpl};
use crawler::spider::candidate_service::{SpiderCandidateService, SpiderCandidateServiceImpl};
use crawler::spider::classification::url_metadata::{
    CrawlerDisposition, CrawlerUrlWriteOutcome, UrlClass,
};
use crawler::spider::classification::url_metadata_repository::{
    UrlMetadataRepository, UrlMetadataRepositoryImpl,
};
use listing_source_core::ListingSourceId;
use std::collections::HashMap;
use std::sync::Arc;
use test_api::*;
use tokio::sync::Barrier;

const POSTGRES: Postgres = Postgres::new("src/crawler/migrations");

fn raw_input_hash() -> Vec<u8> {
    vec![7; 32]
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/// Inserts a ListingSource and its first domain; returns the generated domain ID.
async fn insert_listing_source_with_domain(
    pool: &sqlx::PgPool,
    listing_source_id: ListingSourceId,
    domain: &str,
) -> CrawlerDomainId {
    sqlx::query(
        "INSERT INTO listing_sources (listing_source_id, listing_source_name, listing_source_slug, crawl_enabled, created, updated) \
         VALUES ($1, $2, $3, TRUE, NOW(), NOW())",
    )
    .bind(listing_source_id.as_uuid())
    .bind("Test source")
    .bind("test-source")
    .execute(pool)
    .await
    .unwrap();

    insert_domain_for_listing_source(pool, listing_source_id, domain).await
}

/// Inserts an additional domain row for an already-existing ListingSource.
async fn insert_domain_for_listing_source(
    pool: &sqlx::PgPool,
    listing_source_id: ListingSourceId,
    domain: &str,
) -> CrawlerDomainId {
    let domain_id = CrawlerDomainId::new();
    sqlx::query(
        "INSERT INTO listing_source_domains (domain_id, listing_source_id, listing_source_domain, crawl_root_host) VALUES ($1, $2, $3, $3)",
    )
    .bind(domain_id.as_uuid())
    .bind(listing_source_id.as_uuid())
    .bind(domain)
    .execute(pool)
    .await
    .unwrap();

    domain_id
}

// ============================================================================
// SPIDER CANDIDATE SERVICE
// ============================================================================

// ---------------------------------------------------------------------------
// get_candidates — no eligible listing_sources returns empty vec
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_return_empty_when_no_eligible_candidates_exist() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let candidates = service.get_candidates(10, &[]).await.unwrap();

    assert!(
        candidates.is_empty(),
        "expected no candidates for a fresh schema"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — newly-inserted domain (last_crawled IS NULL) is returned
//                  and carries the correct domain_id
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_return_candidate_with_correct_domain_id_when_never_crawled() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id = insert_listing_source_with_domain(
        &pool,
        listing_source_id,
        "spider-never-crawled.example.com",
    )
    .await;

    let candidates = service.get_candidates(10, &[]).await.unwrap();

    assert_eq!(candidates.len(), 1);
    assert_eq!(
        candidates[0].domain_id, domain_id,
        "candidate must carry the domain_id generated by listing_source_domains"
    );
    assert_eq!(
        candidates[0].listing_source_domain,
        "spider-never-crawled.example.com"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — domain crawled recently is NOT returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_not_return_candidate_when_recently_crawled() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id =
        insert_listing_source_with_domain(&pool, listing_source_id, "spider-recent.example.com")
            .await;

    sqlx::query("UPDATE listing_source_domains SET last_crawled = NOW() WHERE domain_id = $1")
        .bind(domain_id.as_uuid())
        .execute(&pool)
        .await
        .unwrap();

    let candidates = service.get_candidates(10, &[]).await.unwrap();

    assert!(
        !candidates.iter().any(|c| c.domain_id == domain_id),
        "a domain crawled just now should not be returned as a candidate"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — domain crawled more than 7 days ago IS returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_return_candidate_when_crawled_more_than_7_days_ago() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id =
        insert_listing_source_with_domain(&pool, listing_source_id, "spider-stale.example.com")
            .await;

    sqlx::query(
        "UPDATE listing_source_domains SET last_crawled = NOW() - INTERVAL '8 days' WHERE domain_id = $1",
    )
    .bind(domain_id.as_uuid())
    .execute(&pool)
    .await
    .unwrap();

    let candidates = service.get_candidates(10, &[]).await.unwrap();

    assert!(
        candidates.iter().any(|c| c.domain_id == domain_id),
        "stale domain should be returned with its domain_id"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — crawl-disabled listing_sources are excluded
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_not_return_candidate_when_listing_source_crawl_is_disabled() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id =
        insert_listing_source_with_domain(&pool, listing_source_id, "spider-inactive.example.com")
            .await;

    sqlx::query("UPDATE listing_sources SET crawl_enabled = FALSE WHERE listing_source_id = $1")
        .bind(listing_source_id.as_uuid())
        .execute(&pool)
        .await
        .unwrap();

    let candidates = service.get_candidates(10, &[]).await.unwrap();

    assert!(
        !candidates.iter().any(|c| c.domain_id == domain_id),
        "candidates for crawl-disabled listing_sources should be excluded"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — limit is respected
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_respect_limit_when_multiple_candidates_exist() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    for i in 0..3u32 {
        let listing_source_id = ListingSourceId::new();
        insert_listing_source_with_domain(
            &pool,
            listing_source_id,
            &format!("spider-limit-{}.example.com", i),
        )
        .await;
    }

    let candidates = service.get_candidates(2, &[]).await.unwrap();

    assert_eq!(
        candidates.len(),
        2,
        "get_candidates(2) should return at most 2 results"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — multiple domains on the same ListingSource are each returned
//                  with their own domain_id
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_return_each_domain_separately_for_listing_source_with_multiple_domains() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    sqlx::query(
        "INSERT INTO listing_sources (listing_source_id, listing_source_name, listing_source_slug, crawl_enabled, created, updated) \
         VALUES ($1, $2, $3, TRUE, NOW(), NOW())",
    )
    .bind(listing_source_id.as_uuid())
    .bind("Test source")
    .bind("test-source")
    .execute(&pool)
    .await
    .unwrap();

    let domain_id_a =
        insert_domain_for_listing_source(&pool, listing_source_id, "spider-multi-a.example.com")
            .await;
    let domain_id_b =
        insert_domain_for_listing_source(&pool, listing_source_id, "spider-multi-b.example.com")
            .await;

    let candidates = service.get_candidates(10, &[]).await.unwrap();

    let ids: Vec<CrawlerDomainId> = candidates.iter().map(|c| c.domain_id).collect();
    assert!(ids.contains(&domain_id_a), "domain_id_a should be present");
    assert!(ids.contains(&domain_id_b), "domain_id_b should be present");
}

// ---------------------------------------------------------------------------
// get_candidates — listing_source_id on the candidate matches the owning ListingSource
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_return_correct_listing_source_id_on_candidate() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id =
        insert_listing_source_with_domain(&pool, listing_source_id, "spider-source-id.example.com")
            .await;

    let candidates = service.get_candidates(10, &[]).await.unwrap();

    let candidate = candidates
        .iter()
        .find(|c| c.domain_id == domain_id)
        .expect("candidate for the inserted domain should be present");

    assert_eq!(
        candidate.listing_source_id, listing_source_id,
        "candidate.listing_source_id must match the owning ListingSource"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — failure metadata is included for retry policy decisions
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_return_crawl_failure_metadata_on_candidate() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id = insert_listing_source_with_domain(
        &pool,
        listing_source_id,
        "spider-failure-meta.example.com",
    )
    .await;

    sqlx::query(
        "UPDATE listing_source_domains
         SET crawl_failure_count = 2,
             last_crawl_error_kind = 'InsufficientInferenceSample'
         WHERE domain_id = $1",
    )
    .bind(domain_id.as_uuid())
    .execute(&pool)
    .await
    .unwrap();

    let candidates = service.get_candidates(10, &[]).await.unwrap();
    let candidate = candidates
        .iter()
        .find(|c| c.domain_id == domain_id)
        .expect("candidate for the inserted domain should be present");

    assert_eq!(candidate.crawl_failure_count, 2);
    assert_eq!(
        candidate.last_crawl_error_kind.as_deref(),
        Some("InsufficientInferenceSample")
    );
}

// ---------------------------------------------------------------------------
// mark_crawl_failure — stores the caller-provided consecutive count and retry
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_mark_crawl_failure_should_store_count_kind_and_next_crawl_at() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id = insert_listing_source_with_domain(
        &pool,
        listing_source_id,
        "spider-mark-failure.example.com",
    )
    .await;
    let next_crawl_at = time::OffsetDateTime::now_utc() + time::Duration::hours(6);

    service
        .mark_crawl_failure(&domain_id, "InsufficientInferenceSample", 3, next_crawl_at)
        .await
        .unwrap();

    let row: (i32, Option<String>, Option<time::OffsetDateTime>) = sqlx::query_as(
        "SELECT crawl_failure_count, last_crawl_error_kind, next_crawl_at
         FROM listing_source_domains
         WHERE domain_id = $1",
    )
    .bind(domain_id.as_uuid())
    .fetch_one(&pool)
    .await
    .unwrap();

    assert_eq!(row.0, 3);
    assert_eq!(row.1.as_deref(), Some("InsufficientInferenceSample"));
    let stored_next_crawl_at = row.2.expect("next_crawl_at should be stored");
    assert!(
        (stored_next_crawl_at - next_crawl_at).whole_seconds().abs() <= 1,
        "next_crawl_at should match the caller-provided timestamp"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — ordering: NULL last_crawled comes before stale domains
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn spider_should_order_never_crawled_before_stale_crawled() {
    let pool = get_postgres_client().await;
    let service = SpiderCandidateServiceImpl::new(pool.clone());

    let listing_source_id_stale = ListingSourceId::new();
    let listing_source_id_never = ListingSourceId::new();

    let domain_id_stale = insert_listing_source_with_domain(
        &pool,
        listing_source_id_stale,
        "spider-order-stale.example.com",
    )
    .await;
    let domain_id_never = insert_listing_source_with_domain(
        &pool,
        listing_source_id_never,
        "spider-order-never.example.com",
    )
    .await;

    sqlx::query(
        "UPDATE listing_source_domains SET last_crawled = NOW() - INTERVAL '10 days' WHERE domain_id = $1",
    )
    .bind(domain_id_stale.as_uuid())
    .execute(&pool)
    .await
    .unwrap();

    let candidates = service.get_candidates(100, &[]).await.unwrap();

    let pos_never = candidates
        .iter()
        .position(|c| c.domain_id == domain_id_never)
        .expect("never-crawled domain should be in candidates");
    let pos_stale = candidates
        .iter()
        .position(|c| c.domain_id == domain_id_stale)
        .expect("stale domain should be in candidates");

    assert!(
        pos_never < pos_stale,
        "never-crawled (pos {pos_never}) should come before stale (pos {pos_stale})"
    );
}

// ============================================================================
// SCRAPER CANDIDATE SERVICE
// ============================================================================

/// Helper: inserts a product URL into listing_source_urls for the given ListingSource/domain.
async fn insert_product_url(
    pool: &sqlx::PgPool,
    listing_source_id: ListingSourceId,
    domain_id: CrawlerDomainId,
    url: &str,
) {
    let parsed = url::Url::parse(url).unwrap();
    let repo = UrlMetadataRepositoryImpl::new(pool.clone());
    repo.upsert_link(
        &listing_source_id,
        &domain_id,
        &parsed,
        &UrlClass::ProductListing,
    )
    .await
    .unwrap();
}

// ---------------------------------------------------------------------------
// get_candidates — empty DB returns empty vec
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_return_empty_when_no_eligible_candidates_exist() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let candidates = service.get_candidates(10, 100, &[]).await.unwrap();

    assert!(
        candidates.is_empty(),
        "expected no candidates for a fresh schema"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — product URL never scraped IS returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_return_candidate_when_product_url_never_scraped() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id =
        insert_listing_source_with_domain(&pool, listing_source_id, "scraper-never.example.com")
            .await;
    insert_product_url(
        &pool,
        listing_source_id,
        domain_id,
        "https://scraper-never.example.com/p/1",
    )
    .await;

    let candidates = service.get_candidates(10, 100, &[]).await.unwrap();

    assert!(
        candidates
            .iter()
            .any(|c| c.url.as_str() == "https://scraper-never.example.com/p/1"),
        "never-scraped product URL should be returned"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — URL scraped < 1 day ago is NOT returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_not_return_candidate_when_recently_scraped() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id =
        insert_listing_source_with_domain(&pool, listing_source_id, "scraper-recent.example.com")
            .await;
    let url = "https://scraper-recent.example.com/p/1";
    let hash = "b".repeat(64);
    insert_product_url(&pool, listing_source_id, domain_id, url).await;

    // Mark as scraped just now
    sqlx::query("UPDATE listing_source_urls SET last_scraped = NOW(), last_scraped_hash = $1 WHERE url = $2")
        .bind(&hash)
        .bind(url)
        .execute(&pool)
        .await
        .unwrap();

    let candidates = service.get_candidates(10, 100, &[]).await.unwrap();

    assert!(
        !candidates.iter().any(|c| c.url.as_str() == url),
        "URL scraped just now should not be returned"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — URL scraped > 1 day ago IS returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_return_candidate_when_scraped_more_than_1_day_ago() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id =
        insert_listing_source_with_domain(&pool, listing_source_id, "scraper-stale.example.com")
            .await;
    let url = "https://scraper-stale.example.com/p/1";
    insert_product_url(&pool, listing_source_id, domain_id, url).await;

    // Mark as scraped 2 days ago to isolate the time-based filter.
    let old_hash = "old_hash_differs";
    sqlx::query(
        "UPDATE listing_source_urls SET last_scraped = NOW() - INTERVAL '2 days', last_scraped_hash = $1 WHERE url = $2",
    )
    .bind(old_hash)
    .bind(url)
    .execute(&pool)
    .await
    .unwrap();

    let candidates = service.get_candidates(10, 100, &[]).await.unwrap();

    assert!(
        candidates.iter().any(|c| c.url.as_str() == url),
        "URL scraped 2 days ago should be returned"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — non-product URL class is NOT returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_not_return_candidate_when_url_class_is_not_product() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id =
        insert_listing_source_with_domain(&pool, listing_source_id, "scraper-class.example.com")
            .await;

    // Insert as a category URL (not product)
    let url = url::Url::parse("https://scraper-class.example.com/category/1").unwrap();
    let repo = UrlMetadataRepositoryImpl::new(pool.clone());
    repo.upsert_link(&listing_source_id, &domain_id, &url, &UrlClass::Category)
        .await
        .unwrap();

    let candidates = service.get_candidates(10, 100, &[]).await.unwrap();

    assert!(
        !candidates.iter().any(|c| c.url == url),
        "category URL should not be returned as a scraper candidate"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — inactive ListingSource is NOT returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_persist_url_class_other_and_exclude_candidate_when_set_class_is_called() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id = insert_listing_source_with_domain(
        &pool,
        listing_source_id,
        "scraper-set-class.example.com",
    )
    .await;
    let target_url = url::Url::parse("https://scraper-set-class.example.com/p/target").unwrap();
    let other_url = url::Url::parse("https://scraper-set-class.example.com/p/other").unwrap();
    let repo = UrlMetadataRepositoryImpl::new(pool.clone());
    repo.upsert_link(
        &listing_source_id,
        &domain_id,
        &target_url,
        &UrlClass::ProductListing,
    )
    .await
    .unwrap();
    repo.upsert_link(
        &listing_source_id,
        &domain_id,
        &other_url,
        &UrlClass::ProductListing,
    )
    .await
    .unwrap();

    assert_eq!(
        service
            .set_class(&listing_source_id, &target_url, UrlClass::Other, None)
            .await
            .unwrap(),
        CrawlerUrlWriteOutcome::Applied
    );

    let target_class: String = sqlx::query_scalar(
        "SELECT url_class FROM listing_source_urls WHERE listing_source_id = $1 AND url = $2",
    )
    .bind(listing_source_id.as_uuid())
    .bind(target_url.to_string())
    .fetch_one(&pool)
    .await
    .unwrap();
    let other_class: String = sqlx::query_scalar(
        "SELECT url_class FROM listing_source_urls WHERE listing_source_id = $1 AND url = $2",
    )
    .bind(listing_source_id.as_uuid())
    .bind(other_url.to_string())
    .fetch_one(&pool)
    .await
    .unwrap();
    let candidates = service.get_candidates(10, 100, &[]).await.unwrap();

    assert_eq!(target_class, UrlClass::Other.to_string());
    assert_eq!(other_class, UrlClass::ProductListing.to_string());
    assert!(!candidates.iter().any(|c| c.url == target_url));
    assert!(candidates.iter().any(|c| c.url == other_url));
}

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_not_return_candidate_when_listing_source_crawl_is_disabled() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id =
        insert_listing_source_with_domain(&pool, listing_source_id, "scraper-inactive.example.com")
            .await;
    let url = "https://scraper-inactive.example.com/p/1";
    insert_product_url(&pool, listing_source_id, domain_id, url).await;

    sqlx::query("UPDATE listing_sources SET crawl_enabled = FALSE WHERE listing_source_id = $1")
        .bind(listing_source_id.as_uuid())
        .execute(&pool)
        .await
        .unwrap();

    let candidates = service.get_candidates(10, 100, &[]).await.unwrap();

    assert!(
        !candidates.iter().any(|c| c.url.as_str() == url),
        "candidate for crawl-disabled listing source should be excluded"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — sold URLs remain eligible for rechecks
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_return_candidate_when_disposition_is_dormant_sold() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());
    let listing_source_id = ListingSourceId::new();
    let domain_id = insert_listing_source_with_domain(
        &pool,
        listing_source_id,
        "scraper-disposition.example.com",
    )
    .await;
    let sold_url = url::Url::parse("https://scraper-disposition.example.com/p/sold").unwrap();
    let present_url =
        url::Url::parse("https://scraper-disposition.example.com/p/out-of-stock").unwrap();
    let repository = UrlMetadataRepositoryImpl::new(pool.clone());

    for url in [&sold_url, &present_url] {
        repository
            .upsert_link(
                &listing_source_id,
                &domain_id,
                url,
                &UrlClass::ProductListing,
            )
            .await
            .unwrap();
    }
    repository
        .set_disposition(
            &listing_source_id,
            &sold_url,
            CrawlerDisposition::DormantSold,
        )
        .await
        .unwrap();

    let candidates = service.get_candidates(10, 100, &[]).await.unwrap();

    assert!(
        candidates.iter().any(|candidate| candidate.url == sold_url),
        "sold URLs must remain candidates for removal/restock rechecks"
    );
    assert!(
        candidates
            .iter()
            .any(|candidate| candidate.url == present_url)
    );
}

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_mark_removed_should_reactivate_sold_url_after_durable_capture() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());
    let listing_source_id = ListingSourceId::new();
    let domain_id = insert_listing_source_with_domain(
        &pool,
        listing_source_id,
        "scraper-removed-reactivation.example.com",
    )
    .await;
    let url = url::Url::parse("https://scraper-removed-reactivation.example.com/p/1").unwrap();
    let repository = UrlMetadataRepositoryImpl::new(pool.clone());
    repository
        .upsert_link(
            &listing_source_id,
            &domain_id,
            &url,
            &UrlClass::ProductListing,
        )
        .await
        .unwrap();
    repository
        .set_disposition(&listing_source_id, &url, CrawlerDisposition::DormantSold)
        .await
        .unwrap();

    let removal_hash = vec![7; 32];
    assert_eq!(
        service
            .mark_removed(&listing_source_id, &url, &removal_hash, None)
            .await
            .unwrap(),
        CrawlerUrlWriteOutcome::Applied
    );

    let row: (String, Option<Vec<u8>>, Option<time::OffsetDateTime>) = sqlx::query_as(
        "SELECT crawler_disposition, last_captured_raw_input_sha256, last_scraped \
         FROM listing_source_urls WHERE listing_source_id = $1 AND url = $2",
    )
    .bind(listing_source_id.as_uuid())
    .bind(url.as_str())
    .fetch_one(&pool)
    .await
    .unwrap();
    assert_eq!(row.0, CrawlerDisposition::Active.as_str());
    assert_eq!(row.1, Some(removal_hash));
    assert!(row.2.is_some());
    assert!(
        !service
            .get_candidates(10, 100, &[])
            .await
            .unwrap()
            .iter()
            .any(|candidate| candidate.url == url),
        "the removal scrape must obey the usual daily revisit cadence"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — limit is respected
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_respect_limit_when_multiple_candidates_exist() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id =
        insert_listing_source_with_domain(&pool, listing_source_id, "scraper-limit.example.com")
            .await;

    for i in 0..5u32 {
        insert_product_url(
            &pool,
            listing_source_id,
            domain_id,
            &format!("https://scraper-limit.example.com/p/{}", i),
        )
        .await;
    }

    let candidates = service.get_candidates(10, 3, &[]).await.unwrap();

    assert_eq!(
        candidates.len(),
        3,
        "get_candidates(10, 3) should return at most 3 URLs from one selected domain"
    );
}

// ---------------------------------------------------------------------------
// get_candidates - random domain-fair fetching caps domains and URLs per domain
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_cap_domains_and_urls_per_domain_when_fetching_candidates() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let hot_listing_source_id = ListingSourceId::new();
    let hot_domain =
        insert_listing_source_with_domain(&pool, hot_listing_source_id, "fair-hot.example.com")
            .await;
    for i in 0..10u32 {
        insert_product_url(
            &pool,
            hot_listing_source_id,
            hot_domain,
            &format!("https://fair-hot.example.com/p/{i}"),
        )
        .await;
    }

    for domain_idx in 0..4u32 {
        let listing_source_id = ListingSourceId::new();
        let domain_name = format!("fair-cold-{domain_idx}.example.com");
        let domain_id =
            insert_listing_source_with_domain(&pool, listing_source_id, &domain_name).await;
        for url_idx in 0..4u32 {
            insert_product_url(
                &pool,
                listing_source_id,
                domain_id,
                &format!("https://{domain_name}/p/{url_idx}"),
            )
            .await;
        }
    }

    let candidates = service.get_candidates(3, 2, &[]).await.unwrap();

    let mut counts_by_host: HashMap<String, usize> = HashMap::new();
    for candidate in &candidates {
        let host = candidate
            .url
            .host_str()
            .expect("candidate URL should have host")
            .to_string();
        *counts_by_host.entry(host).or_default() += 1;
    }

    assert!(
        counts_by_host.len() <= 3,
        "candidate fetch should select at most 3 domains"
    );
    assert!(
        counts_by_host.values().all(|count| *count <= 2),
        "candidate fetch should select at most 2 URLs per domain"
    );
    assert!(
        candidates.len() <= 6,
        "candidate fetch should return at most N * M URLs"
    );
    assert!(
        counts_by_host
            .get("fair-hot.example.com")
            .copied()
            .unwrap_or(0)
            <= 2,
        "hot domain must not fill the whole fetch"
    );
}

// ---------------------------------------------------------------------------
// get_candidates - selected domain set changes across repeated calls
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_randomize_selected_domains_across_repeated_fetches() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    for i in 0..10u32 {
        let listing_source_id = ListingSourceId::new();
        let domain_name = format!("random-domain-{i}.example.com");
        let domain_id =
            insert_listing_source_with_domain(&pool, listing_source_id, &domain_name).await;
        insert_product_url(
            &pool,
            listing_source_id,
            domain_id,
            &format!("https://{domain_name}/p/1"),
        )
        .await;
    }

    let mut observed_sets: std::collections::HashSet<Vec<String>> =
        std::collections::HashSet::new();
    for _ in 0..20 {
        let candidates = service.get_candidates(3, 1, &[]).await.unwrap();
        let mut hosts: Vec<String> = candidates
            .iter()
            .filter_map(|candidate| candidate.url.host_str().map(str::to_string))
            .collect();
        hosts.sort();
        observed_sets.insert(hosts);
    }

    assert!(
        observed_sets.len() > 1,
        "random domain selection should not return the same host set every time"
    );
}

// ---------------------------------------------------------------------------
// get_candidates - selected URLs inside one domain are oldest first
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_order_urls_within_selected_domain_by_oldest_work_first() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id =
        insert_listing_source_with_domain(&pool, listing_source_id, "fair-order.example.com").await;
    let never_url = "https://fair-order.example.com/p/never";
    let oldest_url = "https://fair-order.example.com/p/oldest";
    let newer_url = "https://fair-order.example.com/p/newer";
    insert_product_url(&pool, listing_source_id, domain_id, newer_url).await;
    insert_product_url(&pool, listing_source_id, domain_id, never_url).await;
    insert_product_url(&pool, listing_source_id, domain_id, oldest_url).await;

    sqlx::query(
        "UPDATE listing_source_urls
         SET last_scraped = NOW() - INTERVAL '2 days',
             last_scraped_hash = 'newer'
         WHERE url = $1",
    )
    .bind(newer_url)
    .execute(&pool)
    .await
    .unwrap();
    sqlx::query(
        "UPDATE listing_source_urls
         SET last_scraped = NOW() - INTERVAL '5 days',
             last_scraped_hash = 'oldest'
         WHERE url = $1",
    )
    .bind(oldest_url)
    .execute(&pool)
    .await
    .unwrap();

    let candidates = service.get_candidates(1, 2, &[]).await.unwrap();
    let urls: Vec<&str> = candidates
        .iter()
        .map(|candidate| candidate.url.as_str())
        .collect();

    assert_eq!(urls, vec![never_url, oldest_url]);
}

// ---------------------------------------------------------------------------
// get_candidates — excluded active domains are NOT returned
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_not_return_candidate_when_domain_is_excluded() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let blocked_listing_source_id = ListingSourceId::new();
    let blocked_domain = insert_listing_source_with_domain(
        &pool,
        blocked_listing_source_id,
        "scraper-blocked.example.com",
    )
    .await;
    insert_product_url(
        &pool,
        blocked_listing_source_id,
        blocked_domain,
        "https://scraper-blocked.example.com/p/1",
    )
    .await;

    let open_listing_source_id = ListingSourceId::new();
    let open_domain = insert_listing_source_with_domain(
        &pool,
        open_listing_source_id,
        "scraper-open.example.com",
    )
    .await;
    insert_product_url(
        &pool,
        open_listing_source_id,
        open_domain,
        "https://scraper-open.example.com/p/1",
    )
    .await;

    let excluded_domains = vec!["scraper-blocked.example.com".to_string()];
    let candidates = service
        .get_candidates(10, 100, &excluded_domains)
        .await
        .unwrap();

    assert!(
        !candidates
            .iter()
            .any(|c| c.url.host_str() == Some("scraper-blocked.example.com")),
        "URL from excluded domain should not be returned"
    );
    assert!(
        candidates
            .iter()
            .any(|c| c.url.host_str() == Some("scraper-open.example.com")),
        "URL from non-excluded domain should still be returned"
    );
}

// ---------------------------------------------------------------------------
// get_candidates — ordering: never-scraped before stale
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_order_never_scraped_before_stale() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id =
        insert_listing_source_with_domain(&pool, listing_source_id, "scraper-order.example.com")
            .await;

    let url_never = "https://scraper-order.example.com/p/never";
    let url_stale = "https://scraper-order.example.com/p/stale";
    insert_product_url(&pool, listing_source_id, domain_id, url_stale).await;
    insert_product_url(&pool, listing_source_id, domain_id, url_never).await;

    // Make the stale one old — scraped 5 days ago with a different hash so it qualifies
    sqlx::query(
        "UPDATE listing_source_urls \
         SET last_scraped = NOW() - INTERVAL '5 days', last_scraped_hash = 'old' \
         WHERE url = $1",
    )
    .bind(url_stale)
    .execute(&pool)
    .await
    .unwrap();

    let candidates = service.get_candidates(100, 100, &[]).await.unwrap();

    let pos_never = candidates
        .iter()
        .position(|c| c.url.as_str() == url_never)
        .expect("never-scraped URL should be in candidates");
    let pos_stale = candidates
        .iter()
        .position(|c| c.url.as_str() == url_stale)
        .expect("stale URL should be in candidates");

    assert!(
        pos_never < pos_stale,
        "never-scraped (pos {pos_never}) should come before stale (pos {pos_stale})"
    );
}

// ---------------------------------------------------------------------------
// mark_as_scraped — sets last_scraped and last_scraped_hash on the row
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_mark_as_scraped_should_set_last_scraped_and_hash() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id =
        insert_listing_source_with_domain(&pool, listing_source_id, "scraper-mark.example.com")
            .await;
    let url_str = "https://scraper-mark.example.com/p/1";
    insert_product_url(&pool, listing_source_id, domain_id, url_str).await;

    let url = url::Url::parse(url_str).unwrap();
    let scraped_hash = "m".repeat(64);

    service
        .mark_as_scraped(
            &listing_source_id,
            &url,
            &scraped_hash,
            "schema-fingerprint",
            &raw_input_hash(),
            CrawlerDisposition::Active,
            None,
        )
        .await
        .unwrap();

    let row: (Option<String>, Option<String>) = sqlx::query_as(
        "SELECT last_scraped_hash, last_scraped::text FROM listing_source_urls WHERE url = $1",
    )
    .bind(url_str)
    .fetch_one(&pool)
    .await
    .unwrap();

    assert_eq!(
        row.0.as_deref(),
        Some(scraped_hash.as_str()),
        "last_scraped_hash should be updated"
    );
    assert!(row.1.is_some(), "last_scraped timestamp should be set");
}

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_completion_should_not_overwrite_newer_dormant_scrape_metadata() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());
    let listing_source_id = ListingSourceId::new();
    let domain_id = insert_listing_source_with_domain(
        &pool,
        listing_source_id,
        "scraper-competing-completion.example.com",
    )
    .await;
    let url = url::Url::parse("https://scraper-competing-completion.example.com/p/1").unwrap();
    insert_product_url(&pool, listing_source_id, domain_id, url.as_str()).await;

    let dormant_raw_input_hash = vec![9; 32];
    assert_eq!(
        service
            .mark_as_scraped(
                &listing_source_id,
                &url,
                "dormant-hash",
                "dormant-schema",
                &dormant_raw_input_hash,
                CrawlerDisposition::DormantSold,
                None,
            )
            .await
            .unwrap(),
        CrawlerUrlWriteOutcome::Applied
    );

    assert_eq!(
        service
            .mark_as_scraped(
                &listing_source_id,
                &url,
                "delayed-active-hash",
                "delayed-active-schema",
                &[8; 32],
                CrawlerDisposition::Active,
                None,
            )
            .await
            .unwrap(),
        CrawlerUrlWriteOutcome::NoopStale
    );

    let row: (String, Option<String>, Option<String>, Option<Vec<u8>>) = sqlx::query_as(
        "SELECT crawler_disposition, last_scraped_hash, last_scraped_schema_fingerprint, \
         last_captured_raw_input_sha256 FROM listing_source_urls WHERE url = $1",
    )
    .bind(url.as_str())
    .fetch_one(&pool)
    .await
    .unwrap();

    assert_eq!(row.0, CrawlerDisposition::DormantSold.as_str());
    assert_eq!(row.1.as_deref(), Some("dormant-hash"));
    assert_eq!(row.2.as_deref(), Some("dormant-schema"));
    assert_eq!(row.3, Some(dormant_raw_input_hash));
}

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_newer_active_completion_should_fence_delayed_active_completion_and_touch() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());
    let listing_source_id = ListingSourceId::new();
    let domain_id = insert_listing_source_with_domain(
        &pool,
        listing_source_id,
        "scraper-active-fence.example.com",
    )
    .await;
    let url = url::Url::parse("https://scraper-active-fence.example.com/p/1").unwrap();
    insert_product_url(&pool, listing_source_id, domain_id, url.as_str()).await;

    let observed_raw_input_sha256: Option<&[u8]> = None;
    let newer_raw_input_sha256 = vec![9; 32];

    assert_eq!(
        service
            .mark_as_scraped(
                &listing_source_id,
                &url,
                "newer-page-hash",
                "newer-schema-fingerprint",
                &newer_raw_input_sha256,
                CrawlerDisposition::Active,
                observed_raw_input_sha256,
            )
            .await
            .unwrap(),
        CrawlerUrlWriteOutcome::Applied
    );

    assert_eq!(
        service
            .mark_as_scraped(
                &listing_source_id,
                &url,
                "delayed-page-hash",
                "delayed-schema-fingerprint",
                &[8; 32],
                CrawlerDisposition::Active,
                observed_raw_input_sha256,
            )
            .await
            .unwrap(),
        CrawlerUrlWriteOutcome::NoopStale
    );
    assert_eq!(
        service
            .touch_scraped(
                &listing_source_id,
                &url,
                "delayed-page-hash",
                "delayed-schema-fingerprint",
                observed_raw_input_sha256,
            )
            .await
            .unwrap(),
        CrawlerUrlWriteOutcome::NoopStale
    );

    let row: (String, Option<String>, Option<String>, Option<Vec<u8>>) = sqlx::query_as(
        "SELECT crawler_disposition, last_scraped_hash, last_scraped_schema_fingerprint, \
         last_captured_raw_input_sha256 FROM listing_source_urls WHERE url = $1",
    )
    .bind(url.as_str())
    .fetch_one(&pool)
    .await
    .unwrap();

    assert_eq!(row.0, CrawlerDisposition::Active.as_str());
    assert_eq!(row.1.as_deref(), Some("newer-page-hash"));
    assert_eq!(row.2.as_deref(), Some("newer-schema-fingerprint"));
    assert_eq!(row.3, Some(newer_raw_input_sha256));
}

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_newer_active_completion_should_fence_delayed_sold_completion() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());
    let listing_source_id = ListingSourceId::new();
    let domain_id = insert_listing_source_with_domain(
        &pool,
        listing_source_id,
        "scraper-sold-fence.example.com",
    )
    .await;
    let url = url::Url::parse("https://scraper-sold-fence.example.com/p/1").unwrap();
    insert_product_url(&pool, listing_source_id, domain_id, url.as_str()).await;

    let observed_raw_input_sha256 = vec![1; 32];
    assert_eq!(
        service
            .mark_as_scraped(
                &listing_source_id,
                &url,
                "observed-page-hash",
                "observed-schema-fingerprint",
                &observed_raw_input_sha256,
                CrawlerDisposition::Active,
                None,
            )
            .await
            .unwrap(),
        CrawlerUrlWriteOutcome::Applied
    );

    let newer_raw_input_sha256 = vec![2; 32];
    assert_eq!(
        service
            .mark_as_scraped(
                &listing_source_id,
                &url,
                "newer-page-hash",
                "newer-schema-fingerprint",
                &newer_raw_input_sha256,
                CrawlerDisposition::Active,
                Some(observed_raw_input_sha256.as_slice()),
            )
            .await
            .unwrap(),
        CrawlerUrlWriteOutcome::Applied
    );

    assert_eq!(
        service
            .mark_as_scraped(
                &listing_source_id,
                &url,
                "delayed-sold-page-hash",
                "delayed-sold-schema-fingerprint",
                &[3; 32],
                CrawlerDisposition::DormantSold,
                Some(observed_raw_input_sha256.as_slice()),
            )
            .await
            .unwrap(),
        CrawlerUrlWriteOutcome::NoopStale
    );

    let row: (String, Option<String>, Option<String>, Option<Vec<u8>>) = sqlx::query_as(
        "SELECT crawler_disposition, last_scraped_hash, last_scraped_schema_fingerprint, \
         last_captured_raw_input_sha256 FROM listing_source_urls WHERE url = $1",
    )
    .bind(url.as_str())
    .fetch_one(&pool)
    .await
    .unwrap();

    assert_eq!(row.0, CrawlerDisposition::Active.as_str());
    assert_eq!(row.1.as_deref(), Some("newer-page-hash"));
    assert_eq!(row.2.as_deref(), Some("newer-schema-fingerprint"));
    assert_eq!(row.3, Some(newer_raw_input_sha256));
}

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_newer_active_completion_should_fence_delayed_disposition_change() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());
    let listing_source_id = ListingSourceId::new();
    let domain_id = insert_listing_source_with_domain(
        &pool,
        listing_source_id,
        "scraper-removal-fence.example.com",
    )
    .await;
    let url = url::Url::parse("https://scraper-removal-fence.example.com/p/1").unwrap();
    insert_product_url(&pool, listing_source_id, domain_id, url.as_str()).await;

    let observed_raw_input_sha256 = vec![4; 32];
    assert_eq!(
        service
            .mark_as_scraped(
                &listing_source_id,
                &url,
                "observed-page-hash",
                "observed-schema-fingerprint",
                &observed_raw_input_sha256,
                CrawlerDisposition::Active,
                None,
            )
            .await
            .unwrap(),
        CrawlerUrlWriteOutcome::Applied
    );

    let newer_raw_input_sha256 = vec![5; 32];
    assert_eq!(
        service
            .mark_as_scraped(
                &listing_source_id,
                &url,
                "newer-page-hash",
                "newer-schema-fingerprint",
                &newer_raw_input_sha256,
                CrawlerDisposition::Active,
                Some(observed_raw_input_sha256.as_slice()),
            )
            .await
            .unwrap(),
        CrawlerUrlWriteOutcome::Applied
    );

    assert_eq!(
        service
            .set_disposition(
                &listing_source_id,
                &url,
                CrawlerDisposition::DormantSold,
                Some(observed_raw_input_sha256.as_slice()),
            )
            .await
            .unwrap(),
        CrawlerUrlWriteOutcome::NoopStale
    );

    let row: (String, Option<String>, Option<String>, Option<Vec<u8>>) = sqlx::query_as(
        "SELECT crawler_disposition, last_scraped_hash, last_scraped_schema_fingerprint, \
         last_captured_raw_input_sha256 FROM listing_source_urls WHERE url = $1",
    )
    .bind(url.as_str())
    .fetch_one(&pool)
    .await
    .unwrap();

    assert_eq!(row.0, CrawlerDisposition::Active.as_str());
    assert_eq!(row.1.as_deref(), Some("newer-page-hash"));
    assert_eq!(row.2.as_deref(), Some("newer-schema-fingerprint"));
    assert_eq!(row.3, Some(newer_raw_input_sha256));
}

#[derive(sqlx::FromRow)]
struct DelayedObserverUrlState {
    url_class: String,
    crawler_disposition: String,
    last_scraped_hash: Option<String>,
    last_captured_raw_input_sha256: Option<Vec<u8>>,
    failure_count: i64,
    last_error_kind: Option<String>,
    last_error_message: Option<String>,
    no_next_retry_at: bool,
    no_last_status_code: bool,
}

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_should_fence_delayed_observer_local_writes_when_newer_active_capture_commits() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());
    let listing_source_id = ListingSourceId::new();
    let domain_id = insert_listing_source_with_domain(
        &pool,
        listing_source_id,
        "scraper-delayed-observer-fence.example.com",
    )
    .await;
    let url = url::Url::parse("https://scraper-delayed-observer-fence.example.com/p/1").unwrap();
    insert_product_url(&pool, listing_source_id, domain_id, url.as_str()).await;

    let observed_raw_input_sha256 = vec![6; 32];
    assert_eq!(
        service
            .mark_as_scraped(
                &listing_source_id,
                &url,
                "observed-page-hash",
                "observed-schema-fingerprint",
                &observed_raw_input_sha256,
                CrawlerDisposition::Active,
                None,
            )
            .await
            .unwrap(),
        CrawlerUrlWriteOutcome::Applied
    );

    let start = Arc::new(Barrier::new(2));
    let newer_committed = Arc::new(Barrier::new(2));
    let newer_raw_input_sha256 = vec![7; 32];

    let newer_task = {
        let service = ScraperCandidateServiceImpl::new(pool.clone());
        let newer_listing_source_id = listing_source_id;
        let url = url.clone();
        let observed_raw_input_sha256 = observed_raw_input_sha256.clone();
        let newer_raw_input_sha256 = newer_raw_input_sha256.clone();
        let start = Arc::clone(&start);
        let newer_committed = Arc::clone(&newer_committed);

        tokio::spawn(async move {
            start.wait().await;
            assert_eq!(
                service
                    .mark_as_scraped(
                        &newer_listing_source_id,
                        &url,
                        "newer-page-hash",
                        "newer-schema-fingerprint",
                        &newer_raw_input_sha256,
                        CrawlerDisposition::Active,
                        Some(observed_raw_input_sha256.as_slice()),
                    )
                    .await
                    .unwrap(),
                CrawlerUrlWriteOutcome::Applied
            );
            newer_committed.wait().await;
        })
    };

    let delayed_task = {
        let service = ScraperCandidateServiceImpl::new(pool.clone());
        let delayed_listing_source_id = listing_source_id;
        let url = url.clone();
        let observed_raw_input_sha256 = observed_raw_input_sha256.clone();
        let start = Arc::clone(&start);
        let newer_committed = Arc::clone(&newer_committed);

        tokio::spawn(async move {
            start.wait().await;
            newer_committed.wait().await;

            assert_eq!(
                service
                    .set_class(
                        &delayed_listing_source_id,
                        &url,
                        UrlClass::Other,
                        Some(observed_raw_input_sha256.as_slice()),
                    )
                    .await
                    .unwrap(),
                CrawlerUrlWriteOutcome::NoopStale
            );
            assert_eq!(
                service
                    .mark_fetch_failure(
                        &delayed_listing_source_id,
                        &url,
                        "DelayedFetchFailure",
                        "delayed observer",
                        Some(500),
                        time::OffsetDateTime::now_utc() + time::Duration::hours(1),
                        Some(observed_raw_input_sha256.as_slice()),
                    )
                    .await
                    .unwrap(),
                CrawlerUrlWriteOutcome::NoopStale
            );
            assert_eq!(
                service
                    .mark_scraper_failure(
                        &delayed_listing_source_id,
                        &url,
                        "DelayedScraperFailure",
                        "delayed observer",
                        Some(observed_raw_input_sha256.as_slice()),
                    )
                    .await
                    .unwrap(),
                CrawlerUrlWriteOutcome::NoopStale
            );
            assert_eq!(
                service
                    .set_disposition(
                        &delayed_listing_source_id,
                        &url,
                        CrawlerDisposition::DormantSold,
                        Some(observed_raw_input_sha256.as_slice()),
                    )
                    .await
                    .unwrap(),
                CrawlerUrlWriteOutcome::NoopStale
            );
        })
    };

    newer_task.await.unwrap();
    delayed_task.await.unwrap();

    let row = sqlx::query_as::<_, DelayedObserverUrlState>(
        "SELECT url_class, crawler_disposition, last_scraped_hash, \
         last_captured_raw_input_sha256, failure_count::bigint AS failure_count, \
         last_error_kind, last_error_message, next_retry_at IS NULL AS no_next_retry_at, \
         last_status_code IS NULL AS no_last_status_code \
         FROM listing_source_urls WHERE url = $1",
    )
    .bind(url.as_str())
    .fetch_one(&pool)
    .await
    .unwrap();

    assert_eq!(row.url_class, UrlClass::ProductListing.as_str());
    assert_eq!(row.crawler_disposition, CrawlerDisposition::Active.as_str());
    assert_eq!(row.last_scraped_hash.as_deref(), Some("newer-page-hash"));
    assert_eq!(
        row.last_captured_raw_input_sha256,
        Some(newer_raw_input_sha256)
    );
    assert_eq!(row.failure_count, 0);
    assert!(row.last_error_kind.is_none());
    assert!(row.last_error_message.is_none());
    assert!(row.no_next_retry_at);
    assert!(row.no_last_status_code);
}

// ---------------------------------------------------------------------------
// mark_as_scraped — after marking, the URL is excluded from get_candidates
//                   (recently scraped)
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_mark_as_scraped_should_exclude_url_from_subsequent_get_candidates() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id = insert_listing_source_with_domain(
        &pool,
        listing_source_id,
        "scraper-roundtrip.example.com",
    )
    .await;
    let url_str = "https://scraper-roundtrip.example.com/p/1";
    let hash = "n".repeat(64);
    insert_product_url(&pool, listing_source_id, domain_id, url_str).await;

    // Confirm it is returned before marking
    let before = service.get_candidates(10, 100, &[]).await.unwrap();
    assert!(
        before.iter().any(|c| c.url.as_str() == url_str),
        "URL should appear before mark_as_scraped"
    );

    let url = url::Url::parse(url_str).unwrap();
    service
        .mark_as_scraped(
            &listing_source_id,
            &url,
            &hash,
            "schema-fingerprint",
            &raw_input_hash(),
            CrawlerDisposition::Active,
            None,
        )
        .await
        .unwrap();

    // After marking with NOW() timestamp it should no longer appear
    let after = service.get_candidates(10, 100, &[]).await.unwrap();
    assert!(
        !after.iter().any(|c| c.url.as_str() == url_str),
        "URL should not appear after mark_as_scraped"
    );
}

// ---------------------------------------------------------------------------
// get_random_product_urls_for_schema_seed — excludes current URL
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_seed_urls_should_exclude_current_url() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id =
        insert_listing_source_with_domain(&pool, listing_source_id, "seed-exclude.example.com")
            .await;

    let exclude_url = "https://seed-exclude.example.com/p/current";
    let other_url = "https://seed-exclude.example.com/p/other";
    insert_product_url(&pool, listing_source_id, domain_id, exclude_url).await;
    insert_product_url(&pool, listing_source_id, domain_id, other_url).await;

    let exclude = url::Url::parse(exclude_url).unwrap();
    let sampled = service
        .get_random_product_urls_for_schema_seed(&listing_source_id, &exclude, 5)
        .await
        .unwrap();

    assert!(
        sampled.iter().all(|u| u.as_str() != exclude_url),
        "excluded URL must never be returned"
    );
    assert!(
        sampled.iter().any(|u| u.as_str() == other_url),
        "another eligible product URL should be sampled"
    );
}

// ---------------------------------------------------------------------------
// get_random_product_urls_for_schema_seed — same ListingSource, product class, and presence
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_seed_urls_should_include_same_listing_source_sold_product_urls() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let seed_listing_source_id = ListingSourceId::new();
    let seed_domain_id = insert_listing_source_with_domain(
        &pool,
        seed_listing_source_id,
        "seed-filters.example.com",
    )
    .await;
    let repo = UrlMetadataRepositoryImpl::new(pool.clone());

    let current_url = url::Url::parse("https://seed-filters.example.com/p/current").unwrap();
    repo.upsert_link(
        &seed_listing_source_id,
        &seed_domain_id,
        &current_url,
        &UrlClass::ProductListing,
    )
    .await
    .unwrap();

    let eligible_url = url::Url::parse("https://seed-filters.example.com/p/eligible").unwrap();
    repo.upsert_link(
        &seed_listing_source_id,
        &seed_domain_id,
        &eligible_url,
        &UrlClass::ProductListing,
    )
    .await
    .unwrap();

    let sold_url = url::Url::parse("https://seed-filters.example.com/p/sold").unwrap();
    repo.upsert_link(
        &seed_listing_source_id,
        &seed_domain_id,
        &sold_url,
        &UrlClass::ProductListing,
    )
    .await
    .unwrap();
    repo.set_disposition(
        &seed_listing_source_id,
        &sold_url,
        CrawlerDisposition::DormantSold,
    )
    .await
    .unwrap();

    let withdrawn_url = url::Url::parse("https://seed-filters.example.com/p/withdrawn").unwrap();
    repo.upsert_link(
        &seed_listing_source_id,
        &seed_domain_id,
        &withdrawn_url,
        &UrlClass::ProductListing,
    )
    .await
    .unwrap();
    repo.set_disposition(
        &seed_listing_source_id,
        &withdrawn_url,
        CrawlerDisposition::DormantSold,
    )
    .await
    .unwrap();

    let category_url =
        url::Url::parse("https://seed-filters.example.com/category/whatever").unwrap();
    repo.upsert_link(
        &seed_listing_source_id,
        &seed_domain_id,
        &category_url,
        &UrlClass::Category,
    )
    .await
    .unwrap();

    let other_listing_source_id = ListingSourceId::new();
    let other_domain_id = insert_listing_source_with_domain(
        &pool,
        other_listing_source_id,
        "seed-other-source.example.com",
    )
    .await;
    let other_listing_source_url =
        url::Url::parse("https://seed-other-source.example.com/p/other").unwrap();
    repo.upsert_link(
        &other_listing_source_id,
        &other_domain_id,
        &other_listing_source_url,
        &UrlClass::ProductListing,
    )
    .await
    .unwrap();

    let sampled = service
        .get_random_product_urls_for_schema_seed(&seed_listing_source_id, &current_url, 20)
        .await
        .unwrap();

    assert!(
        sampled.iter().any(|u| u == &eligible_url),
        "eligible product URL from same ListingSource should be included"
    );
    assert!(
        sampled.iter().all(|u| u != &current_url),
        "current URL must be excluded"
    );
    assert!(
        sampled.iter().any(|u| u == &sold_url),
        "sold product URLs must be included for schema seeding"
    );
    assert!(
        sampled.iter().any(|u| u == &withdrawn_url),
        "a second sold product URL must be included for schema seeding"
    );
    assert!(
        sampled.iter().all(|u| u != &category_url),
        "non-product URLs must be excluded"
    );
    assert!(
        sampled.iter().all(|u| u != &other_listing_source_url),
        "URLs from other listing_sources must be excluded"
    );
}

// ---------------------------------------------------------------------------
// get_random_product_urls_for_schema_seed — limit is respected
// ---------------------------------------------------------------------------

#[serial]
#[aura_integration_test(services = [POSTGRES])]
async fn scraper_seed_urls_should_respect_limit() {
    let pool = get_postgres_client().await;
    let service = ScraperCandidateServiceImpl::new(pool.clone());

    let listing_source_id = ListingSourceId::new();
    let domain_id =
        insert_listing_source_with_domain(&pool, listing_source_id, "seed-limit.example.com").await;

    let current_url = "https://seed-limit.example.com/p/current";
    insert_product_url(&pool, listing_source_id, domain_id, current_url).await;

    for i in 0..6u32 {
        insert_product_url(
            &pool,
            listing_source_id,
            domain_id,
            &format!("https://seed-limit.example.com/p/{i}"),
        )
        .await;
    }

    let exclude = url::Url::parse(current_url).unwrap();
    let sampled = service
        .get_random_product_urls_for_schema_seed(&listing_source_id, &exclude, 3)
        .await
        .unwrap();

    assert_eq!(sampled.len(), 3, "query should respect the requested LIMIT");
}
