[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
time = { version = "0.3.41", features = ["formatting", "parsing", "macros", "serde"] }
rand = "0.9.1"
uuid = { version = "1.17.0", features = ["v4", "v7"] }
thiserror = "2.0.12"

[dev-dependencies]
rstest = "0.25.0"
serde_json = "1.0.140"
quickcheck = "1.0.3"
