[package]
name = "domain-primitives"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
slug = { workspace = true }
strong_id = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["macros", "parsing", "serde"] }
uuid = { workspace = true, features = ["v4", "v7"] }

fake = { workspace = true, optional = true }

[dev-dependencies]
rstest = { workspace = true }
serde_json = { workspace = true }

[features]
default = []
test-data = ["dep:fake"]
